/** Routes centralisées — évite les chemins en dur dans l'app. */
export const ROUTES = {
  home: "/",
  tarifs: "/tarifs",
  conformite: "/conformite",
  guideCommentFaireDevis: "/guide/comment-faire-un-devis",
  guideDevisConforme: "/guide/devis-artisan-conforme",
  devisFacile: "/devis-facile",
  guideFacturationAe: "/guide/facturation-auto-entrepreneur",
  guideTvaArtisan: "/guide/tva-artisan-travaux",
  guideMentionsDevis: "/guide/mentions-obligatoires-devis",
  guideDevisWhatsapp: "/guide/partager-devis-whatsapp",
  blog: "/blog",
  blogDevisPlombier: "/blog/devis-plombier-chiffrage",
  blogFactureAe2026: "/blog/facture-auto-entrepreneur-2026",
  blogDevisElectricien: "/blog/devis-electricien-normes",
  blogRelancerDevis: "/blog/relancer-devis-artisan",
  devisArtisanHub: "/devis-artisan",
  creerDevis: "/creer-devis",
  creerDevisApercu: "/creer-devis/apercu",
  inscription: "/inscription",
  inscriptionConfirmation: "/inscription/confirmation",
  connexion: "/connexion",
  connexionMagicLink: "/connexion/magic-link",
  offline: "/offline",
  dashboard: "/dashboard",
  dashboardDevisList: "/dashboard/devis",
  dashboardFactures: "/dashboard/factures",
  dashboardSettings: "/dashboard/settings",
  dashboardActiver: "/dashboard/activer",
  dashboardStats: "/dashboard/stats",
  dashboardAudit: "/dashboard/audit",
  dashboardSupport: "/dashboard/support",
  dashboardDevisNew: "/dashboard/devis/nouveau",
  dashboardDevis: (id: string) => `/dashboard/devis/${id}`,
  dashboardFacture: (id: string) => `/dashboard/factures/${id}`,
  /** ref = slug lisible (devis-dev-2026-0003) ou token legacy */
  publicDevis: (ref: string) => `/devis/${encodeURIComponent(ref)}`,
  publicFacture: (ref: string) => `/facture/${encodeURIComponent(ref)}`,
  mentionsLegales: "/mentions-legales",
  politiqueConfidentialite: "/politique-confidentialite",
  cgu: "/cgu",
  cgv: "/cgv",
  apiDevisPdf: (id: string) => `/api/devis/${id}/pdf`,
  apiFacturePdf: (id: string) => `/api/factures/${id}/pdf`,
  apiArchiveDevis: (id: string) => `/api/archives/devis/${id}`,
  apiArchiveFacture: (id: string) => `/api/archives/factures/${id}`,
  apiArchiveAttestation: (factureId: string) => `/api/archives/factures/${factureId}/attestation`,
} as const;

export const MARKETING_ROUTES = [
  ROUTES.home,
  ROUTES.tarifs,
  ROUTES.conformite,
  ROUTES.guideCommentFaireDevis,
  ROUTES.guideDevisConforme,
  ROUTES.devisFacile,
  ROUTES.guideFacturationAe,
  ROUTES.guideTvaArtisan,
  ROUTES.guideMentionsDevis,
  ROUTES.guideDevisWhatsapp,
  ROUTES.blog,
  ROUTES.blogDevisPlombier,
  ROUTES.blogFactureAe2026,
  ROUTES.blogDevisElectricien,
  ROUTES.blogRelancerDevis,
  ROUTES.devisArtisanHub,
  ROUTES.creerDevis,
  ROUTES.inscription,
  ROUTES.mentionsLegales,
  ROUTES.politiqueConfidentialite,
  ROUTES.cgu,
  ROUTES.cgv,
] as const;
